// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderService.proto

package com.gkg.bridge.poc.proto;

/**
 * Protobuf type {@code com.gkg.bridge.poc.proto.OrderReply}
 */
public  final class OrderReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gkg.bridge.poc.proto.OrderReply)
    OrderReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderReply.newBuilder() to construct.
  private OrderReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderReply() {
    replyId_ = "";
    requestId_ = "";
    order_ = "";
    login_ = "";
    platformSymbol_ = "";
    replyStatus_ = 0;
    replyReason_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OrderReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OrderReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            replyId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            requestId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            order_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            login_ = s;
            break;
          }
          case 40: {

            serverId_ = input.readInt32();
            break;
          }
          case 49: {

            requestAmount_ = input.readDouble();
            break;
          }
          case 57: {

            executionAmount_ = input.readDouble();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            platformSymbol_ = s;
            break;
          }
          case 73: {

            executionPrice_ = input.readDouble();
            break;
          }
          case 80: {
            int rawValue = input.readEnum();

            replyStatus_ = rawValue;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            replyReason_ = s;
            break;
          }
          case 96: {

            executionTimeStamp_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gkg.bridge.poc.proto.OrderServiceOuterClass.internal_static_com_gkg_bridge_poc_proto_OrderReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gkg.bridge.poc.proto.OrderServiceOuterClass.internal_static_com_gkg_bridge_poc_proto_OrderReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gkg.bridge.poc.proto.OrderReply.class, com.gkg.bridge.poc.proto.OrderReply.Builder.class);
  }

  /**
   * Protobuf enum {@code com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType}
   */
  public enum OrderReplyStatusType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EXECUTED = 0;</code>
     */
    EXECUTED(0),
    /**
     * <code>REJECTED = 1;</code>
     */
    REJECTED(1),
    /**
     * <code>ORST_UNSPECIFIED = 2;</code>
     */
    ORST_UNSPECIFIED(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>EXECUTED = 0;</code>
     */
    public static final int EXECUTED_VALUE = 0;
    /**
     * <code>REJECTED = 1;</code>
     */
    public static final int REJECTED_VALUE = 1;
    /**
     * <code>ORST_UNSPECIFIED = 2;</code>
     */
    public static final int ORST_UNSPECIFIED_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OrderReplyStatusType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OrderReplyStatusType forNumber(int value) {
      switch (value) {
        case 0: return EXECUTED;
        case 1: return REJECTED;
        case 2: return ORST_UNSPECIFIED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OrderReplyStatusType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OrderReplyStatusType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OrderReplyStatusType>() {
            public OrderReplyStatusType findValueByNumber(int number) {
              return OrderReplyStatusType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.gkg.bridge.poc.proto.OrderReply.getDescriptor().getEnumTypes().get(0);
    }

    private static final OrderReplyStatusType[] VALUES = values();

    public static OrderReplyStatusType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OrderReplyStatusType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType)
  }

  public static final int REPLYID_FIELD_NUMBER = 1;
  private volatile java.lang.Object replyId_;
  /**
   * <code>string replyId = 1;</code>
   * @return The replyId.
   */
  public java.lang.String getReplyId() {
    java.lang.Object ref = replyId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      replyId_ = s;
      return s;
    }
  }
  /**
   * <code>string replyId = 1;</code>
   * @return The bytes for replyId.
   */
  public com.google.protobuf.ByteString
      getReplyIdBytes() {
    java.lang.Object ref = replyId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      replyId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUESTID_FIELD_NUMBER = 2;
  private volatile java.lang.Object requestId_;
  /**
   * <code>string requestId = 2;</code>
   * @return The requestId.
   */
  public java.lang.String getRequestId() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestId_ = s;
      return s;
    }
  }
  /**
   * <code>string requestId = 2;</code>
   * @return The bytes for requestId.
   */
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDER_FIELD_NUMBER = 3;
  private volatile java.lang.Object order_;
  /**
   * <code>string order = 3;</code>
   * @return The order.
   */
  public java.lang.String getOrder() {
    java.lang.Object ref = order_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      order_ = s;
      return s;
    }
  }
  /**
   * <code>string order = 3;</code>
   * @return The bytes for order.
   */
  public com.google.protobuf.ByteString
      getOrderBytes() {
    java.lang.Object ref = order_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      order_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOGIN_FIELD_NUMBER = 4;
  private volatile java.lang.Object login_;
  /**
   * <code>string login = 4;</code>
   * @return The login.
   */
  public java.lang.String getLogin() {
    java.lang.Object ref = login_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      login_ = s;
      return s;
    }
  }
  /**
   * <code>string login = 4;</code>
   * @return The bytes for login.
   */
  public com.google.protobuf.ByteString
      getLoginBytes() {
    java.lang.Object ref = login_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      login_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVERID_FIELD_NUMBER = 5;
  private int serverId_;
  /**
   * <code>int32 serverId = 5;</code>
   * @return The serverId.
   */
  public int getServerId() {
    return serverId_;
  }

  public static final int REQUESTAMOUNT_FIELD_NUMBER = 6;
  private double requestAmount_;
  /**
   * <code>double requestAmount = 6;</code>
   * @return The requestAmount.
   */
  public double getRequestAmount() {
    return requestAmount_;
  }

  public static final int EXECUTIONAMOUNT_FIELD_NUMBER = 7;
  private double executionAmount_;
  /**
   * <code>double executionAmount = 7;</code>
   * @return The executionAmount.
   */
  public double getExecutionAmount() {
    return executionAmount_;
  }

  public static final int PLATFORMSYMBOL_FIELD_NUMBER = 8;
  private volatile java.lang.Object platformSymbol_;
  /**
   * <code>string platformSymbol = 8;</code>
   * @return The platformSymbol.
   */
  public java.lang.String getPlatformSymbol() {
    java.lang.Object ref = platformSymbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      platformSymbol_ = s;
      return s;
    }
  }
  /**
   * <code>string platformSymbol = 8;</code>
   * @return The bytes for platformSymbol.
   */
  public com.google.protobuf.ByteString
      getPlatformSymbolBytes() {
    java.lang.Object ref = platformSymbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      platformSymbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXECUTIONPRICE_FIELD_NUMBER = 9;
  private double executionPrice_;
  /**
   * <code>double executionPrice = 9;</code>
   * @return The executionPrice.
   */
  public double getExecutionPrice() {
    return executionPrice_;
  }

  public static final int REPLYSTATUS_FIELD_NUMBER = 10;
  private int replyStatus_;
  /**
   * <code>.com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType replyStatus = 10;</code>
   * @return The enum numeric value on the wire for replyStatus.
   */
  public int getReplyStatusValue() {
    return replyStatus_;
  }
  /**
   * <code>.com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType replyStatus = 10;</code>
   * @return The replyStatus.
   */
  public com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType getReplyStatus() {
    @SuppressWarnings("deprecation")
    com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType result = com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType.valueOf(replyStatus_);
    return result == null ? com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType.UNRECOGNIZED : result;
  }

  public static final int REPLYREASON_FIELD_NUMBER = 11;
  private volatile java.lang.Object replyReason_;
  /**
   * <code>string replyReason = 11;</code>
   * @return The replyReason.
   */
  public java.lang.String getReplyReason() {
    java.lang.Object ref = replyReason_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      replyReason_ = s;
      return s;
    }
  }
  /**
   * <code>string replyReason = 11;</code>
   * @return The bytes for replyReason.
   */
  public com.google.protobuf.ByteString
      getReplyReasonBytes() {
    java.lang.Object ref = replyReason_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      replyReason_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXECUTIONTIMESTAMP_FIELD_NUMBER = 12;
  private long executionTimeStamp_;
  /**
   * <code>int64 executionTimeStamp = 12;</code>
   * @return The executionTimeStamp.
   */
  public long getExecutionTimeStamp() {
    return executionTimeStamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getReplyIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, replyId_);
    }
    if (!getRequestIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, requestId_);
    }
    if (!getOrderBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, order_);
    }
    if (!getLoginBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, login_);
    }
    if (serverId_ != 0) {
      output.writeInt32(5, serverId_);
    }
    if (requestAmount_ != 0D) {
      output.writeDouble(6, requestAmount_);
    }
    if (executionAmount_ != 0D) {
      output.writeDouble(7, executionAmount_);
    }
    if (!getPlatformSymbolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, platformSymbol_);
    }
    if (executionPrice_ != 0D) {
      output.writeDouble(9, executionPrice_);
    }
    if (replyStatus_ != com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType.EXECUTED.getNumber()) {
      output.writeEnum(10, replyStatus_);
    }
    if (!getReplyReasonBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, replyReason_);
    }
    if (executionTimeStamp_ != 0L) {
      output.writeInt64(12, executionTimeStamp_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getReplyIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, replyId_);
    }
    if (!getRequestIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, requestId_);
    }
    if (!getOrderBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, order_);
    }
    if (!getLoginBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, login_);
    }
    if (serverId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, serverId_);
    }
    if (requestAmount_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, requestAmount_);
    }
    if (executionAmount_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, executionAmount_);
    }
    if (!getPlatformSymbolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, platformSymbol_);
    }
    if (executionPrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, executionPrice_);
    }
    if (replyStatus_ != com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType.EXECUTED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, replyStatus_);
    }
    if (!getReplyReasonBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, replyReason_);
    }
    if (executionTimeStamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, executionTimeStamp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gkg.bridge.poc.proto.OrderReply)) {
      return super.equals(obj);
    }
    com.gkg.bridge.poc.proto.OrderReply other = (com.gkg.bridge.poc.proto.OrderReply) obj;

    if (!getReplyId()
        .equals(other.getReplyId())) return false;
    if (!getRequestId()
        .equals(other.getRequestId())) return false;
    if (!getOrder()
        .equals(other.getOrder())) return false;
    if (!getLogin()
        .equals(other.getLogin())) return false;
    if (getServerId()
        != other.getServerId()) return false;
    if (java.lang.Double.doubleToLongBits(getRequestAmount())
        != java.lang.Double.doubleToLongBits(
            other.getRequestAmount())) return false;
    if (java.lang.Double.doubleToLongBits(getExecutionAmount())
        != java.lang.Double.doubleToLongBits(
            other.getExecutionAmount())) return false;
    if (!getPlatformSymbol()
        .equals(other.getPlatformSymbol())) return false;
    if (java.lang.Double.doubleToLongBits(getExecutionPrice())
        != java.lang.Double.doubleToLongBits(
            other.getExecutionPrice())) return false;
    if (replyStatus_ != other.replyStatus_) return false;
    if (!getReplyReason()
        .equals(other.getReplyReason())) return false;
    if (getExecutionTimeStamp()
        != other.getExecutionTimeStamp()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REPLYID_FIELD_NUMBER;
    hash = (53 * hash) + getReplyId().hashCode();
    hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId().hashCode();
    hash = (37 * hash) + ORDER_FIELD_NUMBER;
    hash = (53 * hash) + getOrder().hashCode();
    hash = (37 * hash) + LOGIN_FIELD_NUMBER;
    hash = (53 * hash) + getLogin().hashCode();
    hash = (37 * hash) + SERVERID_FIELD_NUMBER;
    hash = (53 * hash) + getServerId();
    hash = (37 * hash) + REQUESTAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRequestAmount()));
    hash = (37 * hash) + EXECUTIONAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getExecutionAmount()));
    hash = (37 * hash) + PLATFORMSYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getPlatformSymbol().hashCode();
    hash = (37 * hash) + EXECUTIONPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getExecutionPrice()));
    hash = (37 * hash) + REPLYSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + replyStatus_;
    hash = (37 * hash) + REPLYREASON_FIELD_NUMBER;
    hash = (53 * hash) + getReplyReason().hashCode();
    hash = (37 * hash) + EXECUTIONTIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExecutionTimeStamp());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gkg.bridge.poc.proto.OrderReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gkg.bridge.poc.proto.OrderReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gkg.bridge.poc.proto.OrderReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gkg.bridge.poc.proto.OrderReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gkg.bridge.poc.proto.OrderReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gkg.bridge.poc.proto.OrderReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gkg.bridge.poc.proto.OrderReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gkg.bridge.poc.proto.OrderReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gkg.bridge.poc.proto.OrderReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gkg.bridge.poc.proto.OrderReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gkg.bridge.poc.proto.OrderReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gkg.bridge.poc.proto.OrderReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gkg.bridge.poc.proto.OrderReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gkg.bridge.poc.proto.OrderReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gkg.bridge.poc.proto.OrderReply)
      com.gkg.bridge.poc.proto.OrderReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gkg.bridge.poc.proto.OrderServiceOuterClass.internal_static_com_gkg_bridge_poc_proto_OrderReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gkg.bridge.poc.proto.OrderServiceOuterClass.internal_static_com_gkg_bridge_poc_proto_OrderReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gkg.bridge.poc.proto.OrderReply.class, com.gkg.bridge.poc.proto.OrderReply.Builder.class);
    }

    // Construct using com.gkg.bridge.poc.proto.OrderReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      replyId_ = "";

      requestId_ = "";

      order_ = "";

      login_ = "";

      serverId_ = 0;

      requestAmount_ = 0D;

      executionAmount_ = 0D;

      platformSymbol_ = "";

      executionPrice_ = 0D;

      replyStatus_ = 0;

      replyReason_ = "";

      executionTimeStamp_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gkg.bridge.poc.proto.OrderServiceOuterClass.internal_static_com_gkg_bridge_poc_proto_OrderReply_descriptor;
    }

    @java.lang.Override
    public com.gkg.bridge.poc.proto.OrderReply getDefaultInstanceForType() {
      return com.gkg.bridge.poc.proto.OrderReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.gkg.bridge.poc.proto.OrderReply build() {
      com.gkg.bridge.poc.proto.OrderReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gkg.bridge.poc.proto.OrderReply buildPartial() {
      com.gkg.bridge.poc.proto.OrderReply result = new com.gkg.bridge.poc.proto.OrderReply(this);
      result.replyId_ = replyId_;
      result.requestId_ = requestId_;
      result.order_ = order_;
      result.login_ = login_;
      result.serverId_ = serverId_;
      result.requestAmount_ = requestAmount_;
      result.executionAmount_ = executionAmount_;
      result.platformSymbol_ = platformSymbol_;
      result.executionPrice_ = executionPrice_;
      result.replyStatus_ = replyStatus_;
      result.replyReason_ = replyReason_;
      result.executionTimeStamp_ = executionTimeStamp_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gkg.bridge.poc.proto.OrderReply) {
        return mergeFrom((com.gkg.bridge.poc.proto.OrderReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gkg.bridge.poc.proto.OrderReply other) {
      if (other == com.gkg.bridge.poc.proto.OrderReply.getDefaultInstance()) return this;
      if (!other.getReplyId().isEmpty()) {
        replyId_ = other.replyId_;
        onChanged();
      }
      if (!other.getRequestId().isEmpty()) {
        requestId_ = other.requestId_;
        onChanged();
      }
      if (!other.getOrder().isEmpty()) {
        order_ = other.order_;
        onChanged();
      }
      if (!other.getLogin().isEmpty()) {
        login_ = other.login_;
        onChanged();
      }
      if (other.getServerId() != 0) {
        setServerId(other.getServerId());
      }
      if (other.getRequestAmount() != 0D) {
        setRequestAmount(other.getRequestAmount());
      }
      if (other.getExecutionAmount() != 0D) {
        setExecutionAmount(other.getExecutionAmount());
      }
      if (!other.getPlatformSymbol().isEmpty()) {
        platformSymbol_ = other.platformSymbol_;
        onChanged();
      }
      if (other.getExecutionPrice() != 0D) {
        setExecutionPrice(other.getExecutionPrice());
      }
      if (other.replyStatus_ != 0) {
        setReplyStatusValue(other.getReplyStatusValue());
      }
      if (!other.getReplyReason().isEmpty()) {
        replyReason_ = other.replyReason_;
        onChanged();
      }
      if (other.getExecutionTimeStamp() != 0L) {
        setExecutionTimeStamp(other.getExecutionTimeStamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gkg.bridge.poc.proto.OrderReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gkg.bridge.poc.proto.OrderReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object replyId_ = "";
    /**
     * <code>string replyId = 1;</code>
     * @return The replyId.
     */
    public java.lang.String getReplyId() {
      java.lang.Object ref = replyId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        replyId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string replyId = 1;</code>
     * @return The bytes for replyId.
     */
    public com.google.protobuf.ByteString
        getReplyIdBytes() {
      java.lang.Object ref = replyId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        replyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string replyId = 1;</code>
     * @param value The replyId to set.
     * @return This builder for chaining.
     */
    public Builder setReplyId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      replyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string replyId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReplyId() {
      
      replyId_ = getDefaultInstance().getReplyId();
      onChanged();
      return this;
    }
    /**
     * <code>string replyId = 1;</code>
     * @param value The bytes for replyId to set.
     * @return This builder for chaining.
     */
    public Builder setReplyIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      replyId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object requestId_ = "";
    /**
     * <code>string requestId = 2;</code>
     * @return The requestId.
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string requestId = 2;</code>
     * @return The bytes for requestId.
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string requestId = 2;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string requestId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      
      requestId_ = getDefaultInstance().getRequestId();
      onChanged();
      return this;
    }
    /**
     * <code>string requestId = 2;</code>
     * @param value The bytes for requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object order_ = "";
    /**
     * <code>string order = 3;</code>
     * @return The order.
     */
    public java.lang.String getOrder() {
      java.lang.Object ref = order_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        order_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string order = 3;</code>
     * @return The bytes for order.
     */
    public com.google.protobuf.ByteString
        getOrderBytes() {
      java.lang.Object ref = order_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        order_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string order = 3;</code>
     * @param value The order to set.
     * @return This builder for chaining.
     */
    public Builder setOrder(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      order_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string order = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrder() {
      
      order_ = getDefaultInstance().getOrder();
      onChanged();
      return this;
    }
    /**
     * <code>string order = 3;</code>
     * @param value The bytes for order to set.
     * @return This builder for chaining.
     */
    public Builder setOrderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      order_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object login_ = "";
    /**
     * <code>string login = 4;</code>
     * @return The login.
     */
    public java.lang.String getLogin() {
      java.lang.Object ref = login_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        login_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string login = 4;</code>
     * @return The bytes for login.
     */
    public com.google.protobuf.ByteString
        getLoginBytes() {
      java.lang.Object ref = login_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        login_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string login = 4;</code>
     * @param value The login to set.
     * @return This builder for chaining.
     */
    public Builder setLogin(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      login_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string login = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLogin() {
      
      login_ = getDefaultInstance().getLogin();
      onChanged();
      return this;
    }
    /**
     * <code>string login = 4;</code>
     * @param value The bytes for login to set.
     * @return This builder for chaining.
     */
    public Builder setLoginBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      login_ = value;
      onChanged();
      return this;
    }

    private int serverId_ ;
    /**
     * <code>int32 serverId = 5;</code>
     * @return The serverId.
     */
    public int getServerId() {
      return serverId_;
    }
    /**
     * <code>int32 serverId = 5;</code>
     * @param value The serverId to set.
     * @return This builder for chaining.
     */
    public Builder setServerId(int value) {
      
      serverId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 serverId = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerId() {
      
      serverId_ = 0;
      onChanged();
      return this;
    }

    private double requestAmount_ ;
    /**
     * <code>double requestAmount = 6;</code>
     * @return The requestAmount.
     */
    public double getRequestAmount() {
      return requestAmount_;
    }
    /**
     * <code>double requestAmount = 6;</code>
     * @param value The requestAmount to set.
     * @return This builder for chaining.
     */
    public Builder setRequestAmount(double value) {
      
      requestAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double requestAmount = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestAmount() {
      
      requestAmount_ = 0D;
      onChanged();
      return this;
    }

    private double executionAmount_ ;
    /**
     * <code>double executionAmount = 7;</code>
     * @return The executionAmount.
     */
    public double getExecutionAmount() {
      return executionAmount_;
    }
    /**
     * <code>double executionAmount = 7;</code>
     * @param value The executionAmount to set.
     * @return This builder for chaining.
     */
    public Builder setExecutionAmount(double value) {
      
      executionAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double executionAmount = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearExecutionAmount() {
      
      executionAmount_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object platformSymbol_ = "";
    /**
     * <code>string platformSymbol = 8;</code>
     * @return The platformSymbol.
     */
    public java.lang.String getPlatformSymbol() {
      java.lang.Object ref = platformSymbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        platformSymbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string platformSymbol = 8;</code>
     * @return The bytes for platformSymbol.
     */
    public com.google.protobuf.ByteString
        getPlatformSymbolBytes() {
      java.lang.Object ref = platformSymbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platformSymbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string platformSymbol = 8;</code>
     * @param value The platformSymbol to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformSymbol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      platformSymbol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string platformSymbol = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatformSymbol() {
      
      platformSymbol_ = getDefaultInstance().getPlatformSymbol();
      onChanged();
      return this;
    }
    /**
     * <code>string platformSymbol = 8;</code>
     * @param value The bytes for platformSymbol to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      platformSymbol_ = value;
      onChanged();
      return this;
    }

    private double executionPrice_ ;
    /**
     * <code>double executionPrice = 9;</code>
     * @return The executionPrice.
     */
    public double getExecutionPrice() {
      return executionPrice_;
    }
    /**
     * <code>double executionPrice = 9;</code>
     * @param value The executionPrice to set.
     * @return This builder for chaining.
     */
    public Builder setExecutionPrice(double value) {
      
      executionPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double executionPrice = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearExecutionPrice() {
      
      executionPrice_ = 0D;
      onChanged();
      return this;
    }

    private int replyStatus_ = 0;
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType replyStatus = 10;</code>
     * @return The enum numeric value on the wire for replyStatus.
     */
    public int getReplyStatusValue() {
      return replyStatus_;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType replyStatus = 10;</code>
     * @param value The enum numeric value on the wire for replyStatus to set.
     * @return This builder for chaining.
     */
    public Builder setReplyStatusValue(int value) {
      replyStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType replyStatus = 10;</code>
     * @return The replyStatus.
     */
    public com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType getReplyStatus() {
      @SuppressWarnings("deprecation")
      com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType result = com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType.valueOf(replyStatus_);
      return result == null ? com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType replyStatus = 10;</code>
     * @param value The replyStatus to set.
     * @return This builder for chaining.
     */
    public Builder setReplyStatus(com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      replyStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderReply.OrderReplyStatusType replyStatus = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearReplyStatus() {
      
      replyStatus_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object replyReason_ = "";
    /**
     * <code>string replyReason = 11;</code>
     * @return The replyReason.
     */
    public java.lang.String getReplyReason() {
      java.lang.Object ref = replyReason_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        replyReason_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string replyReason = 11;</code>
     * @return The bytes for replyReason.
     */
    public com.google.protobuf.ByteString
        getReplyReasonBytes() {
      java.lang.Object ref = replyReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        replyReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string replyReason = 11;</code>
     * @param value The replyReason to set.
     * @return This builder for chaining.
     */
    public Builder setReplyReason(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      replyReason_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string replyReason = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearReplyReason() {
      
      replyReason_ = getDefaultInstance().getReplyReason();
      onChanged();
      return this;
    }
    /**
     * <code>string replyReason = 11;</code>
     * @param value The bytes for replyReason to set.
     * @return This builder for chaining.
     */
    public Builder setReplyReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      replyReason_ = value;
      onChanged();
      return this;
    }

    private long executionTimeStamp_ ;
    /**
     * <code>int64 executionTimeStamp = 12;</code>
     * @return The executionTimeStamp.
     */
    public long getExecutionTimeStamp() {
      return executionTimeStamp_;
    }
    /**
     * <code>int64 executionTimeStamp = 12;</code>
     * @param value The executionTimeStamp to set.
     * @return This builder for chaining.
     */
    public Builder setExecutionTimeStamp(long value) {
      
      executionTimeStamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 executionTimeStamp = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearExecutionTimeStamp() {
      
      executionTimeStamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.gkg.bridge.poc.proto.OrderReply)
  }

  // @@protoc_insertion_point(class_scope:com.gkg.bridge.poc.proto.OrderReply)
  private static final com.gkg.bridge.poc.proto.OrderReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gkg.bridge.poc.proto.OrderReply();
  }

  public static com.gkg.bridge.poc.proto.OrderReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderReply>
      PARSER = new com.google.protobuf.AbstractParser<OrderReply>() {
    @java.lang.Override
    public OrderReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OrderReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OrderReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gkg.bridge.poc.proto.OrderReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

