// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderService.proto

package com.gkg.bridge.poc.proto;

public interface OrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gkg.bridge.poc.proto.OrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestId = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string requestId = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>string order = 2;</code>
   * @return The order.
   */
  java.lang.String getOrder();
  /**
   * <code>string order = 2;</code>
   * @return The bytes for order.
   */
  com.google.protobuf.ByteString
      getOrderBytes();

  /**
   * <code>string login = 3;</code>
   * @return The login.
   */
  java.lang.String getLogin();
  /**
   * <code>string login = 3;</code>
   * @return The bytes for login.
   */
  com.google.protobuf.ByteString
      getLoginBytes();

  /**
   * <code>string platformGroupName = 4;</code>
   * @return The platformGroupName.
   */
  java.lang.String getPlatformGroupName();
  /**
   * <code>string platformGroupName = 4;</code>
   * @return The bytes for platformGroupName.
   */
  com.google.protobuf.ByteString
      getPlatformGroupNameBytes();

  /**
   * <code>.com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType platformRequestType = 5;</code>
   * @return The enum numeric value on the wire for platformRequestType.
   */
  int getPlatformRequestTypeValue();
  /**
   * <code>.com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType platformRequestType = 5;</code>
   * @return The platformRequestType.
   */
  com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType getPlatformRequestType();

  /**
   * <code>.com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType bridgeOrderType = 6;</code>
   * @return The enum numeric value on the wire for bridgeOrderType.
   */
  int getBridgeOrderTypeValue();
  /**
   * <code>.com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType bridgeOrderType = 6;</code>
   * @return The bridgeOrderType.
   */
  com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType getBridgeOrderType();

  /**
   * <code>.com.gkg.bridge.poc.proto.OrderRequest.OrderSideType platformSide = 7;</code>
   * @return The enum numeric value on the wire for platformSide.
   */
  int getPlatformSideValue();
  /**
   * <code>.com.gkg.bridge.poc.proto.OrderRequest.OrderSideType platformSide = 7;</code>
   * @return The platformSide.
   */
  com.gkg.bridge.poc.proto.OrderRequest.OrderSideType getPlatformSide();

  /**
   * <code>.com.gkg.bridge.poc.proto.OrderRequest.OrderSideType side = 8;</code>
   * @return The enum numeric value on the wire for side.
   */
  int getSideValue();
  /**
   * <code>.com.gkg.bridge.poc.proto.OrderRequest.OrderSideType side = 8;</code>
   * @return The side.
   */
  com.gkg.bridge.poc.proto.OrderRequest.OrderSideType getSide();

  /**
   * <code>double amount = 9;</code>
   * @return The amount.
   */
  double getAmount();

  /**
   * <code>string platformSymbol = 10;</code>
   * @return The platformSymbol.
   */
  java.lang.String getPlatformSymbol();
  /**
   * <code>string platformSymbol = 10;</code>
   * @return The bytes for platformSymbol.
   */
  com.google.protobuf.ByteString
      getPlatformSymbolBytes();

  /**
   * <code>string mainSymbol = 11;</code>
   * @return The mainSymbol.
   */
  java.lang.String getMainSymbol();
  /**
   * <code>string mainSymbol = 11;</code>
   * @return The bytes for mainSymbol.
   */
  com.google.protobuf.ByteString
      getMainSymbolBytes();

  /**
   * <code>string platformSymbolSource = 12;</code>
   * @return The platformSymbolSource.
   */
  java.lang.String getPlatformSymbolSource();
  /**
   * <code>string platformSymbolSource = 12;</code>
   * @return The bytes for platformSymbolSource.
   */
  com.google.protobuf.ByteString
      getPlatformSymbolSourceBytes();

  /**
   * <code>string pricingSymbol = 13;</code>
   * @return The pricingSymbol.
   */
  java.lang.String getPricingSymbol();
  /**
   * <code>string pricingSymbol = 13;</code>
   * @return The bytes for pricingSymbol.
   */
  com.google.protobuf.ByteString
      getPricingSymbolBytes();

  /**
   * <code>double price = 14;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>double adjustedPrice = 15;</code>
   * @return The adjustedPrice.
   */
  double getAdjustedPrice();

  /**
   * <code>double tp = 16;</code>
   * @return The tp.
   */
  double getTp();

  /**
   * <code>double adjustedTPPrice = 17;</code>
   * @return The adjustedTPPrice.
   */
  double getAdjustedTPPrice();

  /**
   * <code>double sl = 18;</code>
   * @return The sl.
   */
  double getSl();

  /**
   * <code>double adjustedSLPrice = 19;</code>
   * @return The adjustedSLPrice.
   */
  double getAdjustedSLPrice();

  /**
   * <code>double platformPrice = 20;</code>
   * @return The platformPrice.
   */
  double getPlatformPrice();

  /**
   * <code>int32 digits = 21;</code>
   * @return The digits.
   */
  int getDigits();

  /**
   * <code>int32 markUp = 22;</code>
   * @return The markUp.
   */
  int getMarkUp();

  /**
   * <code>double tickSize = 23;</code>
   * @return The tickSize.
   */
  double getTickSize();

  /**
   * <code>double contractSize = 24;</code>
   * @return The contractSize.
   */
  double getContractSize();

  /**
   * <code>int64 timeStamp = 25;</code>
   * @return The timeStamp.
   */
  long getTimeStamp();

  /**
   * <code>int32 serverId = 26;</code>
   * @return The serverId.
   */
  int getServerId();
}
