// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderService.proto

package com.gkg.bridge.poc.proto;

public final class OrderServiceOuterClass {
  private OrderServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gkg_bridge_poc_proto_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gkg_bridge_poc_proto_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gkg_bridge_poc_proto_OrderReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gkg_bridge_poc_proto_OrderReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022OrderService.proto\022\030com.gkg.bridge.poc" +
      ".proto\"\313\010\n\014OrderRequest\022\021\n\trequestId\030\001 \001" +
      "(\t\022\r\n\005order\030\002 \001(\t\022\r\n\005login\030\003 \001(\t\022\031\n\021plat" +
      "formGroupName\030\004 \001(\t\022W\n\023platformRequestTy" +
      "pe\030\005 \001(\0162:.com.gkg.bridge.poc.proto.Orde" +
      "rRequest.PlatformRequestType\022O\n\017bridgeOr" +
      "derType\030\006 \001(\01626.com.gkg.bridge.poc.proto" +
      ".OrderRequest.BridgeOrderType\022J\n\014platfor" +
      "mSide\030\007 \001(\01624.com.gkg.bridge.poc.proto.O" +
      "rderRequest.OrderSideType\022B\n\004side\030\010 \001(\0162" +
      "4.com.gkg.bridge.poc.proto.OrderRequest." +
      "OrderSideType\022\016\n\006amount\030\t \001(\001\022\026\n\016platfor" +
      "mSymbol\030\n \001(\t\022\022\n\nmainSymbol\030\013 \001(\t\022\034\n\024pla" +
      "tformSymbolSource\030\014 \001(\t\022\025\n\rpricingSymbol" +
      "\030\r \001(\t\022\r\n\005price\030\016 \001(\001\022\025\n\radjustedPrice\030\017" +
      " \001(\001\022\n\n\002tp\030\020 \001(\001\022\027\n\017adjustedTPPrice\030\021 \001(" +
      "\001\022\n\n\002sl\030\022 \001(\001\022\027\n\017adjustedSLPrice\030\023 \001(\001\022\025" +
      "\n\rplatformPrice\030\024 \001(\001\022\016\n\006digits\030\025 \001(\005\022\016\n" +
      "\006markUp\030\026 \001(\005\022\020\n\010tickSize\030\027 \001(\001\022\024\n\014contr" +
      "actSize\030\030 \001(\001\022\021\n\ttimeStamp\030\031 \001(\003\022\020\n\010serv" +
      "erId\030\032 \001(\005\"\315\001\n\023PlatformRequestType\022\020\n\014MA" +
      "RKET_ORDER\020\000\022\024\n\020LIMIT_ACTIVATION\020\001\022\023\n\017ST" +
      "OP_ACTIVATION\020\002\022\021\n\rTP_ACTIVATION\020\003\022\021\n\rSL" +
      "_ACTIVATION\020\004\022\014\n\010IE_ORDER\020\005\022\026\n\022MARKET_CL" +
      "OSE_ORDER\020\006\022\030\n\024MARKET_STOPOUT_ORDER\020\007\022\023\n" +
      "\017PRT_UNSPECIFIED\020\010\"G\n\017BridgeOrderType\022\n\n" +
      "\006MARKET\020\000\022\t\n\005LIMIT\020\001\022\010\n\004STOP\020\002\022\023\n\017BOT_UN" +
      "SPECIFIED\020\003\"7\n\rOrderSideType\022\007\n\003BUY\020\000\022\010\n" +
      "\004SELL\020\001\022\023\n\017OST_UNSPECIFIED\020\002\"\213\003\n\nOrderRe" +
      "ply\022\017\n\007replyId\030\001 \001(\t\022\021\n\trequestId\030\002 \001(\t\022" +
      "\r\n\005order\030\003 \001(\t\022\r\n\005login\030\004 \001(\t\022\020\n\010serverI" +
      "d\030\005 \001(\005\022\025\n\rrequestAmount\030\006 \001(\001\022\027\n\017execut" +
      "ionAmount\030\007 \001(\001\022\026\n\016platformSymbol\030\010 \001(\t\022" +
      "\026\n\016executionPrice\030\t \001(\001\022N\n\013replyStatus\030\n" +
      " \001(\01629.com.gkg.bridge.poc.proto.OrderRep" +
      "ly.OrderReplyStatusType\022\023\n\013replyReason\030\013" +
      " \001(\t\022\032\n\022executionTimeStamp\030\014 \001(\003\"H\n\024Orde" +
      "rReplyStatusType\022\014\n\010EXECUTED\020\000\022\014\n\010REJECT" +
      "ED\020\001\022\024\n\020ORST_UNSPECIFIED\020\0022l\n\014OrderServi" +
      "ce\022\\\n\014processOrder\022&.com.gkg.bridge.poc." +
      "proto.OrderRequest\032$.com.gkg.bridge.poc." +
      "proto.OrderReplyB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_gkg_bridge_poc_proto_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gkg_bridge_poc_proto_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gkg_bridge_poc_proto_OrderRequest_descriptor,
        new java.lang.String[] { "RequestId", "Order", "Login", "PlatformGroupName", "PlatformRequestType", "BridgeOrderType", "PlatformSide", "Side", "Amount", "PlatformSymbol", "MainSymbol", "PlatformSymbolSource", "PricingSymbol", "Price", "AdjustedPrice", "Tp", "AdjustedTPPrice", "Sl", "AdjustedSLPrice", "PlatformPrice", "Digits", "MarkUp", "TickSize", "ContractSize", "TimeStamp", "ServerId", });
    internal_static_com_gkg_bridge_poc_proto_OrderReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_gkg_bridge_poc_proto_OrderReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gkg_bridge_poc_proto_OrderReply_descriptor,
        new java.lang.String[] { "ReplyId", "RequestId", "Order", "Login", "ServerId", "RequestAmount", "ExecutionAmount", "PlatformSymbol", "ExecutionPrice", "ReplyStatus", "ReplyReason", "ExecutionTimeStamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
