// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderService.proto

package com.gkg.bridge.poc.proto;

/**
 * Protobuf type {@code com.gkg.bridge.poc.proto.OrderRequest}
 */
public  final class OrderRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gkg.bridge.poc.proto.OrderRequest)
    OrderRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderRequest.newBuilder() to construct.
  private OrderRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderRequest() {
    requestId_ = "";
    order_ = "";
    login_ = "";
    platformGroupName_ = "";
    platformRequestType_ = 0;
    bridgeOrderType_ = 0;
    platformSide_ = 0;
    side_ = 0;
    platformSymbol_ = "";
    mainSymbol_ = "";
    platformSymbolSource_ = "";
    pricingSymbol_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OrderRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OrderRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            requestId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            order_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            login_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            platformGroupName_ = s;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            platformRequestType_ = rawValue;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            bridgeOrderType_ = rawValue;
            break;
          }
          case 56: {
            int rawValue = input.readEnum();

            platformSide_ = rawValue;
            break;
          }
          case 64: {
            int rawValue = input.readEnum();

            side_ = rawValue;
            break;
          }
          case 73: {

            amount_ = input.readDouble();
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            platformSymbol_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            mainSymbol_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            platformSymbolSource_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            pricingSymbol_ = s;
            break;
          }
          case 113: {

            price_ = input.readDouble();
            break;
          }
          case 121: {

            adjustedPrice_ = input.readDouble();
            break;
          }
          case 129: {

            tp_ = input.readDouble();
            break;
          }
          case 137: {

            adjustedTPPrice_ = input.readDouble();
            break;
          }
          case 145: {

            sl_ = input.readDouble();
            break;
          }
          case 153: {

            adjustedSLPrice_ = input.readDouble();
            break;
          }
          case 161: {

            platformPrice_ = input.readDouble();
            break;
          }
          case 168: {

            digits_ = input.readInt32();
            break;
          }
          case 176: {

            markUp_ = input.readInt32();
            break;
          }
          case 185: {

            tickSize_ = input.readDouble();
            break;
          }
          case 193: {

            contractSize_ = input.readDouble();
            break;
          }
          case 200: {

            timeStamp_ = input.readInt64();
            break;
          }
          case 208: {

            serverId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gkg.bridge.poc.proto.OrderServiceOuterClass.internal_static_com_gkg_bridge_poc_proto_OrderRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gkg.bridge.poc.proto.OrderServiceOuterClass.internal_static_com_gkg_bridge_poc_proto_OrderRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gkg.bridge.poc.proto.OrderRequest.class, com.gkg.bridge.poc.proto.OrderRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType}
   */
  public enum PlatformRequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MARKET_ORDER = 0;</code>
     */
    MARKET_ORDER(0),
    /**
     * <code>LIMIT_ACTIVATION = 1;</code>
     */
    LIMIT_ACTIVATION(1),
    /**
     * <code>STOP_ACTIVATION = 2;</code>
     */
    STOP_ACTIVATION(2),
    /**
     * <code>TP_ACTIVATION = 3;</code>
     */
    TP_ACTIVATION(3),
    /**
     * <code>SL_ACTIVATION = 4;</code>
     */
    SL_ACTIVATION(4),
    /**
     * <code>IE_ORDER = 5;</code>
     */
    IE_ORDER(5),
    /**
     * <code>MARKET_CLOSE_ORDER = 6;</code>
     */
    MARKET_CLOSE_ORDER(6),
    /**
     * <code>MARKET_STOPOUT_ORDER = 7;</code>
     */
    MARKET_STOPOUT_ORDER(7),
    /**
     * <code>PRT_UNSPECIFIED = 8;</code>
     */
    PRT_UNSPECIFIED(8),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MARKET_ORDER = 0;</code>
     */
    public static final int MARKET_ORDER_VALUE = 0;
    /**
     * <code>LIMIT_ACTIVATION = 1;</code>
     */
    public static final int LIMIT_ACTIVATION_VALUE = 1;
    /**
     * <code>STOP_ACTIVATION = 2;</code>
     */
    public static final int STOP_ACTIVATION_VALUE = 2;
    /**
     * <code>TP_ACTIVATION = 3;</code>
     */
    public static final int TP_ACTIVATION_VALUE = 3;
    /**
     * <code>SL_ACTIVATION = 4;</code>
     */
    public static final int SL_ACTIVATION_VALUE = 4;
    /**
     * <code>IE_ORDER = 5;</code>
     */
    public static final int IE_ORDER_VALUE = 5;
    /**
     * <code>MARKET_CLOSE_ORDER = 6;</code>
     */
    public static final int MARKET_CLOSE_ORDER_VALUE = 6;
    /**
     * <code>MARKET_STOPOUT_ORDER = 7;</code>
     */
    public static final int MARKET_STOPOUT_ORDER_VALUE = 7;
    /**
     * <code>PRT_UNSPECIFIED = 8;</code>
     */
    public static final int PRT_UNSPECIFIED_VALUE = 8;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PlatformRequestType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PlatformRequestType forNumber(int value) {
      switch (value) {
        case 0: return MARKET_ORDER;
        case 1: return LIMIT_ACTIVATION;
        case 2: return STOP_ACTIVATION;
        case 3: return TP_ACTIVATION;
        case 4: return SL_ACTIVATION;
        case 5: return IE_ORDER;
        case 6: return MARKET_CLOSE_ORDER;
        case 7: return MARKET_STOPOUT_ORDER;
        case 8: return PRT_UNSPECIFIED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PlatformRequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PlatformRequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PlatformRequestType>() {
            public PlatformRequestType findValueByNumber(int number) {
              return PlatformRequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.gkg.bridge.poc.proto.OrderRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final PlatformRequestType[] VALUES = values();

    public static PlatformRequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PlatformRequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType)
  }

  /**
   * Protobuf enum {@code com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType}
   */
  public enum BridgeOrderType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MARKET = 0;</code>
     */
    MARKET(0),
    /**
     * <code>LIMIT = 1;</code>
     */
    LIMIT(1),
    /**
     * <code>STOP = 2;</code>
     */
    STOP(2),
    /**
     * <code>BOT_UNSPECIFIED = 3;</code>
     */
    BOT_UNSPECIFIED(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MARKET = 0;</code>
     */
    public static final int MARKET_VALUE = 0;
    /**
     * <code>LIMIT = 1;</code>
     */
    public static final int LIMIT_VALUE = 1;
    /**
     * <code>STOP = 2;</code>
     */
    public static final int STOP_VALUE = 2;
    /**
     * <code>BOT_UNSPECIFIED = 3;</code>
     */
    public static final int BOT_UNSPECIFIED_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BridgeOrderType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static BridgeOrderType forNumber(int value) {
      switch (value) {
        case 0: return MARKET;
        case 1: return LIMIT;
        case 2: return STOP;
        case 3: return BOT_UNSPECIFIED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BridgeOrderType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BridgeOrderType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BridgeOrderType>() {
            public BridgeOrderType findValueByNumber(int number) {
              return BridgeOrderType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.gkg.bridge.poc.proto.OrderRequest.getDescriptor().getEnumTypes().get(1);
    }

    private static final BridgeOrderType[] VALUES = values();

    public static BridgeOrderType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BridgeOrderType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType)
  }

  /**
   * Protobuf enum {@code com.gkg.bridge.poc.proto.OrderRequest.OrderSideType}
   */
  public enum OrderSideType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BUY = 0;</code>
     */
    BUY(0),
    /**
     * <code>SELL = 1;</code>
     */
    SELL(1),
    /**
     * <code>OST_UNSPECIFIED = 2;</code>
     */
    OST_UNSPECIFIED(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>BUY = 0;</code>
     */
    public static final int BUY_VALUE = 0;
    /**
     * <code>SELL = 1;</code>
     */
    public static final int SELL_VALUE = 1;
    /**
     * <code>OST_UNSPECIFIED = 2;</code>
     */
    public static final int OST_UNSPECIFIED_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OrderSideType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OrderSideType forNumber(int value) {
      switch (value) {
        case 0: return BUY;
        case 1: return SELL;
        case 2: return OST_UNSPECIFIED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OrderSideType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OrderSideType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OrderSideType>() {
            public OrderSideType findValueByNumber(int number) {
              return OrderSideType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.gkg.bridge.poc.proto.OrderRequest.getDescriptor().getEnumTypes().get(2);
    }

    private static final OrderSideType[] VALUES = values();

    public static OrderSideType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OrderSideType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.gkg.bridge.poc.proto.OrderRequest.OrderSideType)
  }

  public static final int REQUESTID_FIELD_NUMBER = 1;
  private volatile java.lang.Object requestId_;
  /**
   * <code>string requestId = 1;</code>
   * @return The requestId.
   */
  public java.lang.String getRequestId() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestId_ = s;
      return s;
    }
  }
  /**
   * <code>string requestId = 1;</code>
   * @return The bytes for requestId.
   */
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDER_FIELD_NUMBER = 2;
  private volatile java.lang.Object order_;
  /**
   * <code>string order = 2;</code>
   * @return The order.
   */
  public java.lang.String getOrder() {
    java.lang.Object ref = order_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      order_ = s;
      return s;
    }
  }
  /**
   * <code>string order = 2;</code>
   * @return The bytes for order.
   */
  public com.google.protobuf.ByteString
      getOrderBytes() {
    java.lang.Object ref = order_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      order_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOGIN_FIELD_NUMBER = 3;
  private volatile java.lang.Object login_;
  /**
   * <code>string login = 3;</code>
   * @return The login.
   */
  public java.lang.String getLogin() {
    java.lang.Object ref = login_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      login_ = s;
      return s;
    }
  }
  /**
   * <code>string login = 3;</code>
   * @return The bytes for login.
   */
  public com.google.protobuf.ByteString
      getLoginBytes() {
    java.lang.Object ref = login_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      login_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLATFORMGROUPNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object platformGroupName_;
  /**
   * <code>string platformGroupName = 4;</code>
   * @return The platformGroupName.
   */
  public java.lang.String getPlatformGroupName() {
    java.lang.Object ref = platformGroupName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      platformGroupName_ = s;
      return s;
    }
  }
  /**
   * <code>string platformGroupName = 4;</code>
   * @return The bytes for platformGroupName.
   */
  public com.google.protobuf.ByteString
      getPlatformGroupNameBytes() {
    java.lang.Object ref = platformGroupName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      platformGroupName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLATFORMREQUESTTYPE_FIELD_NUMBER = 5;
  private int platformRequestType_;
  /**
   * <code>.com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType platformRequestType = 5;</code>
   * @return The enum numeric value on the wire for platformRequestType.
   */
  public int getPlatformRequestTypeValue() {
    return platformRequestType_;
  }
  /**
   * <code>.com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType platformRequestType = 5;</code>
   * @return The platformRequestType.
   */
  public com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType getPlatformRequestType() {
    @SuppressWarnings("deprecation")
    com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType result = com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType.valueOf(platformRequestType_);
    return result == null ? com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType.UNRECOGNIZED : result;
  }

  public static final int BRIDGEORDERTYPE_FIELD_NUMBER = 6;
  private int bridgeOrderType_;
  /**
   * <code>.com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType bridgeOrderType = 6;</code>
   * @return The enum numeric value on the wire for bridgeOrderType.
   */
  public int getBridgeOrderTypeValue() {
    return bridgeOrderType_;
  }
  /**
   * <code>.com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType bridgeOrderType = 6;</code>
   * @return The bridgeOrderType.
   */
  public com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType getBridgeOrderType() {
    @SuppressWarnings("deprecation")
    com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType result = com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType.valueOf(bridgeOrderType_);
    return result == null ? com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType.UNRECOGNIZED : result;
  }

  public static final int PLATFORMSIDE_FIELD_NUMBER = 7;
  private int platformSide_;
  /**
   * <code>.com.gkg.bridge.poc.proto.OrderRequest.OrderSideType platformSide = 7;</code>
   * @return The enum numeric value on the wire for platformSide.
   */
  public int getPlatformSideValue() {
    return platformSide_;
  }
  /**
   * <code>.com.gkg.bridge.poc.proto.OrderRequest.OrderSideType platformSide = 7;</code>
   * @return The platformSide.
   */
  public com.gkg.bridge.poc.proto.OrderRequest.OrderSideType getPlatformSide() {
    @SuppressWarnings("deprecation")
    com.gkg.bridge.poc.proto.OrderRequest.OrderSideType result = com.gkg.bridge.poc.proto.OrderRequest.OrderSideType.valueOf(platformSide_);
    return result == null ? com.gkg.bridge.poc.proto.OrderRequest.OrderSideType.UNRECOGNIZED : result;
  }

  public static final int SIDE_FIELD_NUMBER = 8;
  private int side_;
  /**
   * <code>.com.gkg.bridge.poc.proto.OrderRequest.OrderSideType side = 8;</code>
   * @return The enum numeric value on the wire for side.
   */
  public int getSideValue() {
    return side_;
  }
  /**
   * <code>.com.gkg.bridge.poc.proto.OrderRequest.OrderSideType side = 8;</code>
   * @return The side.
   */
  public com.gkg.bridge.poc.proto.OrderRequest.OrderSideType getSide() {
    @SuppressWarnings("deprecation")
    com.gkg.bridge.poc.proto.OrderRequest.OrderSideType result = com.gkg.bridge.poc.proto.OrderRequest.OrderSideType.valueOf(side_);
    return result == null ? com.gkg.bridge.poc.proto.OrderRequest.OrderSideType.UNRECOGNIZED : result;
  }

  public static final int AMOUNT_FIELD_NUMBER = 9;
  private double amount_;
  /**
   * <code>double amount = 9;</code>
   * @return The amount.
   */
  public double getAmount() {
    return amount_;
  }

  public static final int PLATFORMSYMBOL_FIELD_NUMBER = 10;
  private volatile java.lang.Object platformSymbol_;
  /**
   * <code>string platformSymbol = 10;</code>
   * @return The platformSymbol.
   */
  public java.lang.String getPlatformSymbol() {
    java.lang.Object ref = platformSymbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      platformSymbol_ = s;
      return s;
    }
  }
  /**
   * <code>string platformSymbol = 10;</code>
   * @return The bytes for platformSymbol.
   */
  public com.google.protobuf.ByteString
      getPlatformSymbolBytes() {
    java.lang.Object ref = platformSymbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      platformSymbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAINSYMBOL_FIELD_NUMBER = 11;
  private volatile java.lang.Object mainSymbol_;
  /**
   * <code>string mainSymbol = 11;</code>
   * @return The mainSymbol.
   */
  public java.lang.String getMainSymbol() {
    java.lang.Object ref = mainSymbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mainSymbol_ = s;
      return s;
    }
  }
  /**
   * <code>string mainSymbol = 11;</code>
   * @return The bytes for mainSymbol.
   */
  public com.google.protobuf.ByteString
      getMainSymbolBytes() {
    java.lang.Object ref = mainSymbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mainSymbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLATFORMSYMBOLSOURCE_FIELD_NUMBER = 12;
  private volatile java.lang.Object platformSymbolSource_;
  /**
   * <code>string platformSymbolSource = 12;</code>
   * @return The platformSymbolSource.
   */
  public java.lang.String getPlatformSymbolSource() {
    java.lang.Object ref = platformSymbolSource_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      platformSymbolSource_ = s;
      return s;
    }
  }
  /**
   * <code>string platformSymbolSource = 12;</code>
   * @return The bytes for platformSymbolSource.
   */
  public com.google.protobuf.ByteString
      getPlatformSymbolSourceBytes() {
    java.lang.Object ref = platformSymbolSource_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      platformSymbolSource_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICINGSYMBOL_FIELD_NUMBER = 13;
  private volatile java.lang.Object pricingSymbol_;
  /**
   * <code>string pricingSymbol = 13;</code>
   * @return The pricingSymbol.
   */
  public java.lang.String getPricingSymbol() {
    java.lang.Object ref = pricingSymbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pricingSymbol_ = s;
      return s;
    }
  }
  /**
   * <code>string pricingSymbol = 13;</code>
   * @return The bytes for pricingSymbol.
   */
  public com.google.protobuf.ByteString
      getPricingSymbolBytes() {
    java.lang.Object ref = pricingSymbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pricingSymbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_FIELD_NUMBER = 14;
  private double price_;
  /**
   * <code>double price = 14;</code>
   * @return The price.
   */
  public double getPrice() {
    return price_;
  }

  public static final int ADJUSTEDPRICE_FIELD_NUMBER = 15;
  private double adjustedPrice_;
  /**
   * <code>double adjustedPrice = 15;</code>
   * @return The adjustedPrice.
   */
  public double getAdjustedPrice() {
    return adjustedPrice_;
  }

  public static final int TP_FIELD_NUMBER = 16;
  private double tp_;
  /**
   * <code>double tp = 16;</code>
   * @return The tp.
   */
  public double getTp() {
    return tp_;
  }

  public static final int ADJUSTEDTPPRICE_FIELD_NUMBER = 17;
  private double adjustedTPPrice_;
  /**
   * <code>double adjustedTPPrice = 17;</code>
   * @return The adjustedTPPrice.
   */
  public double getAdjustedTPPrice() {
    return adjustedTPPrice_;
  }

  public static final int SL_FIELD_NUMBER = 18;
  private double sl_;
  /**
   * <code>double sl = 18;</code>
   * @return The sl.
   */
  public double getSl() {
    return sl_;
  }

  public static final int ADJUSTEDSLPRICE_FIELD_NUMBER = 19;
  private double adjustedSLPrice_;
  /**
   * <code>double adjustedSLPrice = 19;</code>
   * @return The adjustedSLPrice.
   */
  public double getAdjustedSLPrice() {
    return adjustedSLPrice_;
  }

  public static final int PLATFORMPRICE_FIELD_NUMBER = 20;
  private double platformPrice_;
  /**
   * <code>double platformPrice = 20;</code>
   * @return The platformPrice.
   */
  public double getPlatformPrice() {
    return platformPrice_;
  }

  public static final int DIGITS_FIELD_NUMBER = 21;
  private int digits_;
  /**
   * <code>int32 digits = 21;</code>
   * @return The digits.
   */
  public int getDigits() {
    return digits_;
  }

  public static final int MARKUP_FIELD_NUMBER = 22;
  private int markUp_;
  /**
   * <code>int32 markUp = 22;</code>
   * @return The markUp.
   */
  public int getMarkUp() {
    return markUp_;
  }

  public static final int TICKSIZE_FIELD_NUMBER = 23;
  private double tickSize_;
  /**
   * <code>double tickSize = 23;</code>
   * @return The tickSize.
   */
  public double getTickSize() {
    return tickSize_;
  }

  public static final int CONTRACTSIZE_FIELD_NUMBER = 24;
  private double contractSize_;
  /**
   * <code>double contractSize = 24;</code>
   * @return The contractSize.
   */
  public double getContractSize() {
    return contractSize_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 25;
  private long timeStamp_;
  /**
   * <code>int64 timeStamp = 25;</code>
   * @return The timeStamp.
   */
  public long getTimeStamp() {
    return timeStamp_;
  }

  public static final int SERVERID_FIELD_NUMBER = 26;
  private int serverId_;
  /**
   * <code>int32 serverId = 26;</code>
   * @return The serverId.
   */
  public int getServerId() {
    return serverId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRequestIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
    }
    if (!getOrderBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, order_);
    }
    if (!getLoginBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, login_);
    }
    if (!getPlatformGroupNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, platformGroupName_);
    }
    if (platformRequestType_ != com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType.MARKET_ORDER.getNumber()) {
      output.writeEnum(5, platformRequestType_);
    }
    if (bridgeOrderType_ != com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType.MARKET.getNumber()) {
      output.writeEnum(6, bridgeOrderType_);
    }
    if (platformSide_ != com.gkg.bridge.poc.proto.OrderRequest.OrderSideType.BUY.getNumber()) {
      output.writeEnum(7, platformSide_);
    }
    if (side_ != com.gkg.bridge.poc.proto.OrderRequest.OrderSideType.BUY.getNumber()) {
      output.writeEnum(8, side_);
    }
    if (amount_ != 0D) {
      output.writeDouble(9, amount_);
    }
    if (!getPlatformSymbolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, platformSymbol_);
    }
    if (!getMainSymbolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, mainSymbol_);
    }
    if (!getPlatformSymbolSourceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, platformSymbolSource_);
    }
    if (!getPricingSymbolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, pricingSymbol_);
    }
    if (price_ != 0D) {
      output.writeDouble(14, price_);
    }
    if (adjustedPrice_ != 0D) {
      output.writeDouble(15, adjustedPrice_);
    }
    if (tp_ != 0D) {
      output.writeDouble(16, tp_);
    }
    if (adjustedTPPrice_ != 0D) {
      output.writeDouble(17, adjustedTPPrice_);
    }
    if (sl_ != 0D) {
      output.writeDouble(18, sl_);
    }
    if (adjustedSLPrice_ != 0D) {
      output.writeDouble(19, adjustedSLPrice_);
    }
    if (platformPrice_ != 0D) {
      output.writeDouble(20, platformPrice_);
    }
    if (digits_ != 0) {
      output.writeInt32(21, digits_);
    }
    if (markUp_ != 0) {
      output.writeInt32(22, markUp_);
    }
    if (tickSize_ != 0D) {
      output.writeDouble(23, tickSize_);
    }
    if (contractSize_ != 0D) {
      output.writeDouble(24, contractSize_);
    }
    if (timeStamp_ != 0L) {
      output.writeInt64(25, timeStamp_);
    }
    if (serverId_ != 0) {
      output.writeInt32(26, serverId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRequestIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
    }
    if (!getOrderBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, order_);
    }
    if (!getLoginBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, login_);
    }
    if (!getPlatformGroupNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, platformGroupName_);
    }
    if (platformRequestType_ != com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType.MARKET_ORDER.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, platformRequestType_);
    }
    if (bridgeOrderType_ != com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType.MARKET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, bridgeOrderType_);
    }
    if (platformSide_ != com.gkg.bridge.poc.proto.OrderRequest.OrderSideType.BUY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, platformSide_);
    }
    if (side_ != com.gkg.bridge.poc.proto.OrderRequest.OrderSideType.BUY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, side_);
    }
    if (amount_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, amount_);
    }
    if (!getPlatformSymbolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, platformSymbol_);
    }
    if (!getMainSymbolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, mainSymbol_);
    }
    if (!getPlatformSymbolSourceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, platformSymbolSource_);
    }
    if (!getPricingSymbolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, pricingSymbol_);
    }
    if (price_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(14, price_);
    }
    if (adjustedPrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(15, adjustedPrice_);
    }
    if (tp_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(16, tp_);
    }
    if (adjustedTPPrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(17, adjustedTPPrice_);
    }
    if (sl_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(18, sl_);
    }
    if (adjustedSLPrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(19, adjustedSLPrice_);
    }
    if (platformPrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(20, platformPrice_);
    }
    if (digits_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(21, digits_);
    }
    if (markUp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(22, markUp_);
    }
    if (tickSize_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(23, tickSize_);
    }
    if (contractSize_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(24, contractSize_);
    }
    if (timeStamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(25, timeStamp_);
    }
    if (serverId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(26, serverId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gkg.bridge.poc.proto.OrderRequest)) {
      return super.equals(obj);
    }
    com.gkg.bridge.poc.proto.OrderRequest other = (com.gkg.bridge.poc.proto.OrderRequest) obj;

    if (!getRequestId()
        .equals(other.getRequestId())) return false;
    if (!getOrder()
        .equals(other.getOrder())) return false;
    if (!getLogin()
        .equals(other.getLogin())) return false;
    if (!getPlatformGroupName()
        .equals(other.getPlatformGroupName())) return false;
    if (platformRequestType_ != other.platformRequestType_) return false;
    if (bridgeOrderType_ != other.bridgeOrderType_) return false;
    if (platformSide_ != other.platformSide_) return false;
    if (side_ != other.side_) return false;
    if (java.lang.Double.doubleToLongBits(getAmount())
        != java.lang.Double.doubleToLongBits(
            other.getAmount())) return false;
    if (!getPlatformSymbol()
        .equals(other.getPlatformSymbol())) return false;
    if (!getMainSymbol()
        .equals(other.getMainSymbol())) return false;
    if (!getPlatformSymbolSource()
        .equals(other.getPlatformSymbolSource())) return false;
    if (!getPricingSymbol()
        .equals(other.getPricingSymbol())) return false;
    if (java.lang.Double.doubleToLongBits(getPrice())
        != java.lang.Double.doubleToLongBits(
            other.getPrice())) return false;
    if (java.lang.Double.doubleToLongBits(getAdjustedPrice())
        != java.lang.Double.doubleToLongBits(
            other.getAdjustedPrice())) return false;
    if (java.lang.Double.doubleToLongBits(getTp())
        != java.lang.Double.doubleToLongBits(
            other.getTp())) return false;
    if (java.lang.Double.doubleToLongBits(getAdjustedTPPrice())
        != java.lang.Double.doubleToLongBits(
            other.getAdjustedTPPrice())) return false;
    if (java.lang.Double.doubleToLongBits(getSl())
        != java.lang.Double.doubleToLongBits(
            other.getSl())) return false;
    if (java.lang.Double.doubleToLongBits(getAdjustedSLPrice())
        != java.lang.Double.doubleToLongBits(
            other.getAdjustedSLPrice())) return false;
    if (java.lang.Double.doubleToLongBits(getPlatformPrice())
        != java.lang.Double.doubleToLongBits(
            other.getPlatformPrice())) return false;
    if (getDigits()
        != other.getDigits()) return false;
    if (getMarkUp()
        != other.getMarkUp()) return false;
    if (java.lang.Double.doubleToLongBits(getTickSize())
        != java.lang.Double.doubleToLongBits(
            other.getTickSize())) return false;
    if (java.lang.Double.doubleToLongBits(getContractSize())
        != java.lang.Double.doubleToLongBits(
            other.getContractSize())) return false;
    if (getTimeStamp()
        != other.getTimeStamp()) return false;
    if (getServerId()
        != other.getServerId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId().hashCode();
    hash = (37 * hash) + ORDER_FIELD_NUMBER;
    hash = (53 * hash) + getOrder().hashCode();
    hash = (37 * hash) + LOGIN_FIELD_NUMBER;
    hash = (53 * hash) + getLogin().hashCode();
    hash = (37 * hash) + PLATFORMGROUPNAME_FIELD_NUMBER;
    hash = (53 * hash) + getPlatformGroupName().hashCode();
    hash = (37 * hash) + PLATFORMREQUESTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + platformRequestType_;
    hash = (37 * hash) + BRIDGEORDERTYPE_FIELD_NUMBER;
    hash = (53 * hash) + bridgeOrderType_;
    hash = (37 * hash) + PLATFORMSIDE_FIELD_NUMBER;
    hash = (53 * hash) + platformSide_;
    hash = (37 * hash) + SIDE_FIELD_NUMBER;
    hash = (53 * hash) + side_;
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAmount()));
    hash = (37 * hash) + PLATFORMSYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getPlatformSymbol().hashCode();
    hash = (37 * hash) + MAINSYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getMainSymbol().hashCode();
    hash = (37 * hash) + PLATFORMSYMBOLSOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getPlatformSymbolSource().hashCode();
    hash = (37 * hash) + PRICINGSYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getPricingSymbol().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrice()));
    hash = (37 * hash) + ADJUSTEDPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAdjustedPrice()));
    hash = (37 * hash) + TP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTp()));
    hash = (37 * hash) + ADJUSTEDTPPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAdjustedTPPrice()));
    hash = (37 * hash) + SL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSl()));
    hash = (37 * hash) + ADJUSTEDSLPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAdjustedSLPrice()));
    hash = (37 * hash) + PLATFORMPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPlatformPrice()));
    hash = (37 * hash) + DIGITS_FIELD_NUMBER;
    hash = (53 * hash) + getDigits();
    hash = (37 * hash) + MARKUP_FIELD_NUMBER;
    hash = (53 * hash) + getMarkUp();
    hash = (37 * hash) + TICKSIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTickSize()));
    hash = (37 * hash) + CONTRACTSIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getContractSize()));
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeStamp());
    hash = (37 * hash) + SERVERID_FIELD_NUMBER;
    hash = (53 * hash) + getServerId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gkg.bridge.poc.proto.OrderRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gkg.bridge.poc.proto.OrderRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gkg.bridge.poc.proto.OrderRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gkg.bridge.poc.proto.OrderRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gkg.bridge.poc.proto.OrderRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gkg.bridge.poc.proto.OrderRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gkg.bridge.poc.proto.OrderRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gkg.bridge.poc.proto.OrderRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gkg.bridge.poc.proto.OrderRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gkg.bridge.poc.proto.OrderRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gkg.bridge.poc.proto.OrderRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gkg.bridge.poc.proto.OrderRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gkg.bridge.poc.proto.OrderRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gkg.bridge.poc.proto.OrderRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gkg.bridge.poc.proto.OrderRequest)
      com.gkg.bridge.poc.proto.OrderRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gkg.bridge.poc.proto.OrderServiceOuterClass.internal_static_com_gkg_bridge_poc_proto_OrderRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gkg.bridge.poc.proto.OrderServiceOuterClass.internal_static_com_gkg_bridge_poc_proto_OrderRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gkg.bridge.poc.proto.OrderRequest.class, com.gkg.bridge.poc.proto.OrderRequest.Builder.class);
    }

    // Construct using com.gkg.bridge.poc.proto.OrderRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestId_ = "";

      order_ = "";

      login_ = "";

      platformGroupName_ = "";

      platformRequestType_ = 0;

      bridgeOrderType_ = 0;

      platformSide_ = 0;

      side_ = 0;

      amount_ = 0D;

      platformSymbol_ = "";

      mainSymbol_ = "";

      platformSymbolSource_ = "";

      pricingSymbol_ = "";

      price_ = 0D;

      adjustedPrice_ = 0D;

      tp_ = 0D;

      adjustedTPPrice_ = 0D;

      sl_ = 0D;

      adjustedSLPrice_ = 0D;

      platformPrice_ = 0D;

      digits_ = 0;

      markUp_ = 0;

      tickSize_ = 0D;

      contractSize_ = 0D;

      timeStamp_ = 0L;

      serverId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gkg.bridge.poc.proto.OrderServiceOuterClass.internal_static_com_gkg_bridge_poc_proto_OrderRequest_descriptor;
    }

    @java.lang.Override
    public com.gkg.bridge.poc.proto.OrderRequest getDefaultInstanceForType() {
      return com.gkg.bridge.poc.proto.OrderRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.gkg.bridge.poc.proto.OrderRequest build() {
      com.gkg.bridge.poc.proto.OrderRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gkg.bridge.poc.proto.OrderRequest buildPartial() {
      com.gkg.bridge.poc.proto.OrderRequest result = new com.gkg.bridge.poc.proto.OrderRequest(this);
      result.requestId_ = requestId_;
      result.order_ = order_;
      result.login_ = login_;
      result.platformGroupName_ = platformGroupName_;
      result.platformRequestType_ = platformRequestType_;
      result.bridgeOrderType_ = bridgeOrderType_;
      result.platformSide_ = platformSide_;
      result.side_ = side_;
      result.amount_ = amount_;
      result.platformSymbol_ = platformSymbol_;
      result.mainSymbol_ = mainSymbol_;
      result.platformSymbolSource_ = platformSymbolSource_;
      result.pricingSymbol_ = pricingSymbol_;
      result.price_ = price_;
      result.adjustedPrice_ = adjustedPrice_;
      result.tp_ = tp_;
      result.adjustedTPPrice_ = adjustedTPPrice_;
      result.sl_ = sl_;
      result.adjustedSLPrice_ = adjustedSLPrice_;
      result.platformPrice_ = platformPrice_;
      result.digits_ = digits_;
      result.markUp_ = markUp_;
      result.tickSize_ = tickSize_;
      result.contractSize_ = contractSize_;
      result.timeStamp_ = timeStamp_;
      result.serverId_ = serverId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gkg.bridge.poc.proto.OrderRequest) {
        return mergeFrom((com.gkg.bridge.poc.proto.OrderRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gkg.bridge.poc.proto.OrderRequest other) {
      if (other == com.gkg.bridge.poc.proto.OrderRequest.getDefaultInstance()) return this;
      if (!other.getRequestId().isEmpty()) {
        requestId_ = other.requestId_;
        onChanged();
      }
      if (!other.getOrder().isEmpty()) {
        order_ = other.order_;
        onChanged();
      }
      if (!other.getLogin().isEmpty()) {
        login_ = other.login_;
        onChanged();
      }
      if (!other.getPlatformGroupName().isEmpty()) {
        platformGroupName_ = other.platformGroupName_;
        onChanged();
      }
      if (other.platformRequestType_ != 0) {
        setPlatformRequestTypeValue(other.getPlatformRequestTypeValue());
      }
      if (other.bridgeOrderType_ != 0) {
        setBridgeOrderTypeValue(other.getBridgeOrderTypeValue());
      }
      if (other.platformSide_ != 0) {
        setPlatformSideValue(other.getPlatformSideValue());
      }
      if (other.side_ != 0) {
        setSideValue(other.getSideValue());
      }
      if (other.getAmount() != 0D) {
        setAmount(other.getAmount());
      }
      if (!other.getPlatformSymbol().isEmpty()) {
        platformSymbol_ = other.platformSymbol_;
        onChanged();
      }
      if (!other.getMainSymbol().isEmpty()) {
        mainSymbol_ = other.mainSymbol_;
        onChanged();
      }
      if (!other.getPlatformSymbolSource().isEmpty()) {
        platformSymbolSource_ = other.platformSymbolSource_;
        onChanged();
      }
      if (!other.getPricingSymbol().isEmpty()) {
        pricingSymbol_ = other.pricingSymbol_;
        onChanged();
      }
      if (other.getPrice() != 0D) {
        setPrice(other.getPrice());
      }
      if (other.getAdjustedPrice() != 0D) {
        setAdjustedPrice(other.getAdjustedPrice());
      }
      if (other.getTp() != 0D) {
        setTp(other.getTp());
      }
      if (other.getAdjustedTPPrice() != 0D) {
        setAdjustedTPPrice(other.getAdjustedTPPrice());
      }
      if (other.getSl() != 0D) {
        setSl(other.getSl());
      }
      if (other.getAdjustedSLPrice() != 0D) {
        setAdjustedSLPrice(other.getAdjustedSLPrice());
      }
      if (other.getPlatformPrice() != 0D) {
        setPlatformPrice(other.getPlatformPrice());
      }
      if (other.getDigits() != 0) {
        setDigits(other.getDigits());
      }
      if (other.getMarkUp() != 0) {
        setMarkUp(other.getMarkUp());
      }
      if (other.getTickSize() != 0D) {
        setTickSize(other.getTickSize());
      }
      if (other.getContractSize() != 0D) {
        setContractSize(other.getContractSize());
      }
      if (other.getTimeStamp() != 0L) {
        setTimeStamp(other.getTimeStamp());
      }
      if (other.getServerId() != 0) {
        setServerId(other.getServerId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gkg.bridge.poc.proto.OrderRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gkg.bridge.poc.proto.OrderRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object requestId_ = "";
    /**
     * <code>string requestId = 1;</code>
     * @return The requestId.
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string requestId = 1;</code>
     * @return The bytes for requestId.
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string requestId = 1;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string requestId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      
      requestId_ = getDefaultInstance().getRequestId();
      onChanged();
      return this;
    }
    /**
     * <code>string requestId = 1;</code>
     * @param value The bytes for requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object order_ = "";
    /**
     * <code>string order = 2;</code>
     * @return The order.
     */
    public java.lang.String getOrder() {
      java.lang.Object ref = order_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        order_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string order = 2;</code>
     * @return The bytes for order.
     */
    public com.google.protobuf.ByteString
        getOrderBytes() {
      java.lang.Object ref = order_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        order_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string order = 2;</code>
     * @param value The order to set.
     * @return This builder for chaining.
     */
    public Builder setOrder(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      order_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string order = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrder() {
      
      order_ = getDefaultInstance().getOrder();
      onChanged();
      return this;
    }
    /**
     * <code>string order = 2;</code>
     * @param value The bytes for order to set.
     * @return This builder for chaining.
     */
    public Builder setOrderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      order_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object login_ = "";
    /**
     * <code>string login = 3;</code>
     * @return The login.
     */
    public java.lang.String getLogin() {
      java.lang.Object ref = login_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        login_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string login = 3;</code>
     * @return The bytes for login.
     */
    public com.google.protobuf.ByteString
        getLoginBytes() {
      java.lang.Object ref = login_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        login_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string login = 3;</code>
     * @param value The login to set.
     * @return This builder for chaining.
     */
    public Builder setLogin(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      login_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string login = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLogin() {
      
      login_ = getDefaultInstance().getLogin();
      onChanged();
      return this;
    }
    /**
     * <code>string login = 3;</code>
     * @param value The bytes for login to set.
     * @return This builder for chaining.
     */
    public Builder setLoginBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      login_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object platformGroupName_ = "";
    /**
     * <code>string platformGroupName = 4;</code>
     * @return The platformGroupName.
     */
    public java.lang.String getPlatformGroupName() {
      java.lang.Object ref = platformGroupName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        platformGroupName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string platformGroupName = 4;</code>
     * @return The bytes for platformGroupName.
     */
    public com.google.protobuf.ByteString
        getPlatformGroupNameBytes() {
      java.lang.Object ref = platformGroupName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platformGroupName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string platformGroupName = 4;</code>
     * @param value The platformGroupName to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformGroupName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      platformGroupName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string platformGroupName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatformGroupName() {
      
      platformGroupName_ = getDefaultInstance().getPlatformGroupName();
      onChanged();
      return this;
    }
    /**
     * <code>string platformGroupName = 4;</code>
     * @param value The bytes for platformGroupName to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformGroupNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      platformGroupName_ = value;
      onChanged();
      return this;
    }

    private int platformRequestType_ = 0;
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType platformRequestType = 5;</code>
     * @return The enum numeric value on the wire for platformRequestType.
     */
    public int getPlatformRequestTypeValue() {
      return platformRequestType_;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType platformRequestType = 5;</code>
     * @param value The enum numeric value on the wire for platformRequestType to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformRequestTypeValue(int value) {
      platformRequestType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType platformRequestType = 5;</code>
     * @return The platformRequestType.
     */
    public com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType getPlatformRequestType() {
      @SuppressWarnings("deprecation")
      com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType result = com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType.valueOf(platformRequestType_);
      return result == null ? com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType platformRequestType = 5;</code>
     * @param value The platformRequestType to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformRequestType(com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      platformRequestType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.PlatformRequestType platformRequestType = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatformRequestType() {
      
      platformRequestType_ = 0;
      onChanged();
      return this;
    }

    private int bridgeOrderType_ = 0;
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType bridgeOrderType = 6;</code>
     * @return The enum numeric value on the wire for bridgeOrderType.
     */
    public int getBridgeOrderTypeValue() {
      return bridgeOrderType_;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType bridgeOrderType = 6;</code>
     * @param value The enum numeric value on the wire for bridgeOrderType to set.
     * @return This builder for chaining.
     */
    public Builder setBridgeOrderTypeValue(int value) {
      bridgeOrderType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType bridgeOrderType = 6;</code>
     * @return The bridgeOrderType.
     */
    public com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType getBridgeOrderType() {
      @SuppressWarnings("deprecation")
      com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType result = com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType.valueOf(bridgeOrderType_);
      return result == null ? com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType bridgeOrderType = 6;</code>
     * @param value The bridgeOrderType to set.
     * @return This builder for chaining.
     */
    public Builder setBridgeOrderType(com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      bridgeOrderType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.BridgeOrderType bridgeOrderType = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearBridgeOrderType() {
      
      bridgeOrderType_ = 0;
      onChanged();
      return this;
    }

    private int platformSide_ = 0;
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.OrderSideType platformSide = 7;</code>
     * @return The enum numeric value on the wire for platformSide.
     */
    public int getPlatformSideValue() {
      return platformSide_;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.OrderSideType platformSide = 7;</code>
     * @param value The enum numeric value on the wire for platformSide to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformSideValue(int value) {
      platformSide_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.OrderSideType platformSide = 7;</code>
     * @return The platformSide.
     */
    public com.gkg.bridge.poc.proto.OrderRequest.OrderSideType getPlatformSide() {
      @SuppressWarnings("deprecation")
      com.gkg.bridge.poc.proto.OrderRequest.OrderSideType result = com.gkg.bridge.poc.proto.OrderRequest.OrderSideType.valueOf(platformSide_);
      return result == null ? com.gkg.bridge.poc.proto.OrderRequest.OrderSideType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.OrderSideType platformSide = 7;</code>
     * @param value The platformSide to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformSide(com.gkg.bridge.poc.proto.OrderRequest.OrderSideType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      platformSide_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.OrderSideType platformSide = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatformSide() {
      
      platformSide_ = 0;
      onChanged();
      return this;
    }

    private int side_ = 0;
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.OrderSideType side = 8;</code>
     * @return The enum numeric value on the wire for side.
     */
    public int getSideValue() {
      return side_;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.OrderSideType side = 8;</code>
     * @param value The enum numeric value on the wire for side to set.
     * @return This builder for chaining.
     */
    public Builder setSideValue(int value) {
      side_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.OrderSideType side = 8;</code>
     * @return The side.
     */
    public com.gkg.bridge.poc.proto.OrderRequest.OrderSideType getSide() {
      @SuppressWarnings("deprecation")
      com.gkg.bridge.poc.proto.OrderRequest.OrderSideType result = com.gkg.bridge.poc.proto.OrderRequest.OrderSideType.valueOf(side_);
      return result == null ? com.gkg.bridge.poc.proto.OrderRequest.OrderSideType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.OrderSideType side = 8;</code>
     * @param value The side to set.
     * @return This builder for chaining.
     */
    public Builder setSide(com.gkg.bridge.poc.proto.OrderRequest.OrderSideType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      side_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.gkg.bridge.poc.proto.OrderRequest.OrderSideType side = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSide() {
      
      side_ = 0;
      onChanged();
      return this;
    }

    private double amount_ ;
    /**
     * <code>double amount = 9;</code>
     * @return The amount.
     */
    public double getAmount() {
      return amount_;
    }
    /**
     * <code>double amount = 9;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(double value) {
      
      amount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double amount = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      
      amount_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object platformSymbol_ = "";
    /**
     * <code>string platformSymbol = 10;</code>
     * @return The platformSymbol.
     */
    public java.lang.String getPlatformSymbol() {
      java.lang.Object ref = platformSymbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        platformSymbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string platformSymbol = 10;</code>
     * @return The bytes for platformSymbol.
     */
    public com.google.protobuf.ByteString
        getPlatformSymbolBytes() {
      java.lang.Object ref = platformSymbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platformSymbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string platformSymbol = 10;</code>
     * @param value The platformSymbol to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformSymbol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      platformSymbol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string platformSymbol = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatformSymbol() {
      
      platformSymbol_ = getDefaultInstance().getPlatformSymbol();
      onChanged();
      return this;
    }
    /**
     * <code>string platformSymbol = 10;</code>
     * @param value The bytes for platformSymbol to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      platformSymbol_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mainSymbol_ = "";
    /**
     * <code>string mainSymbol = 11;</code>
     * @return The mainSymbol.
     */
    public java.lang.String getMainSymbol() {
      java.lang.Object ref = mainSymbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mainSymbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mainSymbol = 11;</code>
     * @return The bytes for mainSymbol.
     */
    public com.google.protobuf.ByteString
        getMainSymbolBytes() {
      java.lang.Object ref = mainSymbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mainSymbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mainSymbol = 11;</code>
     * @param value The mainSymbol to set.
     * @return This builder for chaining.
     */
    public Builder setMainSymbol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mainSymbol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mainSymbol = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearMainSymbol() {
      
      mainSymbol_ = getDefaultInstance().getMainSymbol();
      onChanged();
      return this;
    }
    /**
     * <code>string mainSymbol = 11;</code>
     * @param value The bytes for mainSymbol to set.
     * @return This builder for chaining.
     */
    public Builder setMainSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mainSymbol_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object platformSymbolSource_ = "";
    /**
     * <code>string platformSymbolSource = 12;</code>
     * @return The platformSymbolSource.
     */
    public java.lang.String getPlatformSymbolSource() {
      java.lang.Object ref = platformSymbolSource_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        platformSymbolSource_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string platformSymbolSource = 12;</code>
     * @return The bytes for platformSymbolSource.
     */
    public com.google.protobuf.ByteString
        getPlatformSymbolSourceBytes() {
      java.lang.Object ref = platformSymbolSource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platformSymbolSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string platformSymbolSource = 12;</code>
     * @param value The platformSymbolSource to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformSymbolSource(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      platformSymbolSource_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string platformSymbolSource = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatformSymbolSource() {
      
      platformSymbolSource_ = getDefaultInstance().getPlatformSymbolSource();
      onChanged();
      return this;
    }
    /**
     * <code>string platformSymbolSource = 12;</code>
     * @param value The bytes for platformSymbolSource to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformSymbolSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      platformSymbolSource_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pricingSymbol_ = "";
    /**
     * <code>string pricingSymbol = 13;</code>
     * @return The pricingSymbol.
     */
    public java.lang.String getPricingSymbol() {
      java.lang.Object ref = pricingSymbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pricingSymbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pricingSymbol = 13;</code>
     * @return The bytes for pricingSymbol.
     */
    public com.google.protobuf.ByteString
        getPricingSymbolBytes() {
      java.lang.Object ref = pricingSymbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pricingSymbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pricingSymbol = 13;</code>
     * @param value The pricingSymbol to set.
     * @return This builder for chaining.
     */
    public Builder setPricingSymbol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pricingSymbol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pricingSymbol = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearPricingSymbol() {
      
      pricingSymbol_ = getDefaultInstance().getPricingSymbol();
      onChanged();
      return this;
    }
    /**
     * <code>string pricingSymbol = 13;</code>
     * @param value The bytes for pricingSymbol to set.
     * @return This builder for chaining.
     */
    public Builder setPricingSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pricingSymbol_ = value;
      onChanged();
      return this;
    }

    private double price_ ;
    /**
     * <code>double price = 14;</code>
     * @return The price.
     */
    public double getPrice() {
      return price_;
    }
    /**
     * <code>double price = 14;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(double value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double price = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      
      price_ = 0D;
      onChanged();
      return this;
    }

    private double adjustedPrice_ ;
    /**
     * <code>double adjustedPrice = 15;</code>
     * @return The adjustedPrice.
     */
    public double getAdjustedPrice() {
      return adjustedPrice_;
    }
    /**
     * <code>double adjustedPrice = 15;</code>
     * @param value The adjustedPrice to set.
     * @return This builder for chaining.
     */
    public Builder setAdjustedPrice(double value) {
      
      adjustedPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double adjustedPrice = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearAdjustedPrice() {
      
      adjustedPrice_ = 0D;
      onChanged();
      return this;
    }

    private double tp_ ;
    /**
     * <code>double tp = 16;</code>
     * @return The tp.
     */
    public double getTp() {
      return tp_;
    }
    /**
     * <code>double tp = 16;</code>
     * @param value The tp to set.
     * @return This builder for chaining.
     */
    public Builder setTp(double value) {
      
      tp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double tp = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearTp() {
      
      tp_ = 0D;
      onChanged();
      return this;
    }

    private double adjustedTPPrice_ ;
    /**
     * <code>double adjustedTPPrice = 17;</code>
     * @return The adjustedTPPrice.
     */
    public double getAdjustedTPPrice() {
      return adjustedTPPrice_;
    }
    /**
     * <code>double adjustedTPPrice = 17;</code>
     * @param value The adjustedTPPrice to set.
     * @return This builder for chaining.
     */
    public Builder setAdjustedTPPrice(double value) {
      
      adjustedTPPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double adjustedTPPrice = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearAdjustedTPPrice() {
      
      adjustedTPPrice_ = 0D;
      onChanged();
      return this;
    }

    private double sl_ ;
    /**
     * <code>double sl = 18;</code>
     * @return The sl.
     */
    public double getSl() {
      return sl_;
    }
    /**
     * <code>double sl = 18;</code>
     * @param value The sl to set.
     * @return This builder for chaining.
     */
    public Builder setSl(double value) {
      
      sl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double sl = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearSl() {
      
      sl_ = 0D;
      onChanged();
      return this;
    }

    private double adjustedSLPrice_ ;
    /**
     * <code>double adjustedSLPrice = 19;</code>
     * @return The adjustedSLPrice.
     */
    public double getAdjustedSLPrice() {
      return adjustedSLPrice_;
    }
    /**
     * <code>double adjustedSLPrice = 19;</code>
     * @param value The adjustedSLPrice to set.
     * @return This builder for chaining.
     */
    public Builder setAdjustedSLPrice(double value) {
      
      adjustedSLPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double adjustedSLPrice = 19;</code>
     * @return This builder for chaining.
     */
    public Builder clearAdjustedSLPrice() {
      
      adjustedSLPrice_ = 0D;
      onChanged();
      return this;
    }

    private double platformPrice_ ;
    /**
     * <code>double platformPrice = 20;</code>
     * @return The platformPrice.
     */
    public double getPlatformPrice() {
      return platformPrice_;
    }
    /**
     * <code>double platformPrice = 20;</code>
     * @param value The platformPrice to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformPrice(double value) {
      
      platformPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double platformPrice = 20;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatformPrice() {
      
      platformPrice_ = 0D;
      onChanged();
      return this;
    }

    private int digits_ ;
    /**
     * <code>int32 digits = 21;</code>
     * @return The digits.
     */
    public int getDigits() {
      return digits_;
    }
    /**
     * <code>int32 digits = 21;</code>
     * @param value The digits to set.
     * @return This builder for chaining.
     */
    public Builder setDigits(int value) {
      
      digits_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 digits = 21;</code>
     * @return This builder for chaining.
     */
    public Builder clearDigits() {
      
      digits_ = 0;
      onChanged();
      return this;
    }

    private int markUp_ ;
    /**
     * <code>int32 markUp = 22;</code>
     * @return The markUp.
     */
    public int getMarkUp() {
      return markUp_;
    }
    /**
     * <code>int32 markUp = 22;</code>
     * @param value The markUp to set.
     * @return This builder for chaining.
     */
    public Builder setMarkUp(int value) {
      
      markUp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 markUp = 22;</code>
     * @return This builder for chaining.
     */
    public Builder clearMarkUp() {
      
      markUp_ = 0;
      onChanged();
      return this;
    }

    private double tickSize_ ;
    /**
     * <code>double tickSize = 23;</code>
     * @return The tickSize.
     */
    public double getTickSize() {
      return tickSize_;
    }
    /**
     * <code>double tickSize = 23;</code>
     * @param value The tickSize to set.
     * @return This builder for chaining.
     */
    public Builder setTickSize(double value) {
      
      tickSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double tickSize = 23;</code>
     * @return This builder for chaining.
     */
    public Builder clearTickSize() {
      
      tickSize_ = 0D;
      onChanged();
      return this;
    }

    private double contractSize_ ;
    /**
     * <code>double contractSize = 24;</code>
     * @return The contractSize.
     */
    public double getContractSize() {
      return contractSize_;
    }
    /**
     * <code>double contractSize = 24;</code>
     * @param value The contractSize to set.
     * @return This builder for chaining.
     */
    public Builder setContractSize(double value) {
      
      contractSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double contractSize = 24;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractSize() {
      
      contractSize_ = 0D;
      onChanged();
      return this;
    }

    private long timeStamp_ ;
    /**
     * <code>int64 timeStamp = 25;</code>
     * @return The timeStamp.
     */
    public long getTimeStamp() {
      return timeStamp_;
    }
    /**
     * <code>int64 timeStamp = 25;</code>
     * @param value The timeStamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimeStamp(long value) {
      
      timeStamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timeStamp = 25;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeStamp() {
      
      timeStamp_ = 0L;
      onChanged();
      return this;
    }

    private int serverId_ ;
    /**
     * <code>int32 serverId = 26;</code>
     * @return The serverId.
     */
    public int getServerId() {
      return serverId_;
    }
    /**
     * <code>int32 serverId = 26;</code>
     * @param value The serverId to set.
     * @return This builder for chaining.
     */
    public Builder setServerId(int value) {
      
      serverId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 serverId = 26;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerId() {
      
      serverId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.gkg.bridge.poc.proto.OrderRequest)
  }

  // @@protoc_insertion_point(class_scope:com.gkg.bridge.poc.proto.OrderRequest)
  private static final com.gkg.bridge.poc.proto.OrderRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gkg.bridge.poc.proto.OrderRequest();
  }

  public static com.gkg.bridge.poc.proto.OrderRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderRequest>
      PARSER = new com.google.protobuf.AbstractParser<OrderRequest>() {
    @java.lang.Override
    public OrderRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OrderRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OrderRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gkg.bridge.poc.proto.OrderRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

